// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3kO_yMSo8YdXOjv08xgfSDsE95ebHw0A',
    appId: '1:706526343804:web:f5714692cef73e36ae4ff9',
    messagingSenderId: '706526343804',
    projectId: 'test-89240',
    authDomain: 'test-89240.firebaseapp.com',
    storageBucket: 'test-89240.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAv4a6ilMsYU22dKUvZaofr8UiLhGRXSw',
    appId: '1:706526343804:android:75a9addda76d9ff1ae4ff9',
    messagingSenderId: '706526343804',
    projectId: 'test-89240',
    storageBucket: 'test-89240.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcbPGxpkrMk8wQpfgDYN_PkTAihD9-BzY',
    appId: '1:706526343804:ios:460764e50ea590c3ae4ff9',
    messagingSenderId: '706526343804',
    projectId: 'test-89240',
    storageBucket: 'test-89240.appspot.com',
    iosBundleId: 'com.bishal.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcbPGxpkrMk8wQpfgDYN_PkTAihD9-BzY',
    appId: '1:706526343804:ios:640101b8b1b8793cae4ff9',
    messagingSenderId: '706526343804',
    projectId: 'test-89240',
    storageBucket: 'test-89240.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3kO_yMSo8YdXOjv08xgfSDsE95ebHw0A',
    appId: '1:706526343804:web:a5c5093b308670a8ae4ff9',
    messagingSenderId: '706526343804',
    projectId: 'test-89240',
    authDomain: 'test-89240.firebaseapp.com',
    storageBucket: 'test-89240.appspot.com',
  );
}
